---
- hosts: All
  remote_user: root
  tasks:
   # Boilerplate stuff
    apt: upgrade_cache=yes
    apt: upgrade=yes
    apt: upgrade=dist
   # End boilerplate stuff 
   # Begin default apps
    apt: name={{ item }} state=present
    with_items:
      - htop
      - tmux
      - screen
      - pastebinit
    # End generalized
