---
- hosts: Controllers
  remote_user: root
  tasks:
    #TODO: network (NIC) config
    apt: name=ntp state=present
    template: src=  dest=/etc/ntp.conf 
    		# 	  NTP.conf with server {{NTP_SERVER}} iburst
				  # restrict -4 default kod notrap nomodify
      #             restrict -6 default kod notrap nomodify
    service: name=ntp state=restarted
    #Openstack Prereq packages
    apt: name=python-software-properties state=present
    shell: add-apt-repository cloud-archive:juno
    apt: update_cache=yes
    apt: upgrade=dist
    #Openstack Prereq END
    #Openstack Database installation
    apt: name={{items}} state=present
    with_items:
      - mariadb-server
      - python-mysqldb
    template: src= dest=/etc/mysql/my.cnf
    # Update /etc/mysql/my.cnf with;
    # [mysqld]
	# ...
	# bind-address = {{local_ip}}
	# default-storage-engine = innodb
	# innodb_file_per_table
	# collation-server = utf8_general_ci
	# init-connect = 'SET NAMES utf8'
	# character-set-server = utf8
	service: name=mysql state=restarted
	shell: mysql_secure_installation